# Variables that determine the name of your output files
location: "Staadion"
date: "13_05"
device: "Pixel"
constellations: "GPS"

# Decide which conversions do you need for calculation
ubx_conversion: True
raw_data_conversion: True
pos_conversion: True

# Distance between ground truth receiver and the device
systematic_error: 0.137

# Providers for raw data conversion (NLP or FLP can be used as well)
provider: "GPS"

# If distance between 2 consecutive ground truth is lower than this threshold then they will be disregarded from data
epsilon: 0.2
